// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AlbumView: typeof import('./src/components/AlbumView.vue')['default']
    ArtistView: typeof import('./src/components/ArtistView.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/index/Footer.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MainPage: typeof import('./src/components/index/MainPage.vue')['default']
    PageHeader: typeof import('./src/components/index/PageHeader.vue')['default']
    PlayControl: typeof import('./src/components/index/PlayControl.vue')['default']
    Queue: typeof import('./src/components/Queue.vue')['default']
  }
}

export { }
